import { CommunityResource, TeamProfile, ContributorRank, ContributorBadge } from '@/types'

// ═══════════════════════════════════════
// 教学资源广场 — 15份精选资源
// ═══════════════════════════════════════
export const COMMUNITY_RESOURCES: CommunityResource[] = [
  { id:'cr1',title:'乡村小学趣味科学实验20例',description:'不需要实验室器材，用矿泉水瓶、吸管、橡皮筋等日常物品就能做的20个科学实验。每个实验配有详细步骤、原理解释和课堂管理小贴士。在4个支教点反复验证，孩子们每次都沸腾。',category:'activity',grade:'grade3-4',subject:'科学',fileType:'PDF',fileSize:'2.3MB',downloads:847,rating:4.9,teamName:'凡星支教队',location:'四川筠连',tags:['科学实验','低成本','动手实践','已验证'],author:{ id:'v1',name:'小张老师',avatar:'/images/community/author-volunteer-zhang.webp',role:'volunteer',verified:true,badge:'凡星支教队',teamName:'凡星支教队',location:'四川筠连'},createdAt:'2026-04-15',featured:true},
  { id:'cr2',title:'筠连红色文化教案——赵一曼专题',description:'围绕抗日英雄赵一曼烈士的生平设计的一堂45分钟红色教育课。包含赵一曼在宜宾的生活轨迹、狱中给儿子的信、互动问答环节。特别适合四川地区支教队使用，能引起孩子们的强烈共鸣。',category:'lesson_plan',grade:'grade5-6',subject:'语文',fileType:'PDF',fileSize:'1.8MB',downloads:623,rating:4.8,teamName:'凡星支教队',location:'四川筠连',tags:['红色教育','赵一曼','四川本地','45分钟'],author:{ id:'u1',name:'黄寒阳',avatar:'/images/community/author-volunteer-zhang.webp',role:'volunteer',verified:true,badge:'凡星支教队·队长',teamName:'凡星支教队',location:'四川筠连'},createdAt:'2026-04-20',featured:true},
  { id:'cr3',title:'古诗词手势舞教学视频合集',description:'将12首小学必背古诗编成手势舞。每首诗配3分钟视频，分解动作+完整演示。在云南、四川5个支教点使用后学生古诗背诵速度提升约40%，关键是孩子们真的很快乐。',category:'video',grade:'grade1-2',subject:'语文',fileType:'MP4',fileSize:'680MB',downloads:1203,rating:4.9,teamName:'彩云之南志愿队',location:'云南西双版纳',tags:['古诗词','手势舞','低年级','视频教学'],author:{ id:'a2',name:'雪莉',avatar:'🌸',role:'volunteer',verified:true,badge:'彩云之南志愿队·队长',teamName:'彩云之南志愿队',location:'云南西双版纳'},createdAt:'2026-03-08',featured:true},
  { id:'cr4',title:'数学游戏化教学——数字接龙30种玩法',description:'30种数字游戏覆盖加减乘除、分数、小数等知识点。每种游戏标明适合年级、所需材料（基本不需要额外材料）、游戏时长。最受欢迎的数字炸弹游戏连最不爱数学的孩子都举手抢答。',category:'worksheet',grade:'grade3-4',subject:'数学',fileType:'PDF',fileSize:'3.1MB',downloads:956,rating:4.7,teamName:'阳光支教队',location:'四川美姑',tags:['数学','游戏化教学','30种玩法','全年级'],author:{ id:'a1',name:'婷婷',avatar:'🌻',role:'volunteer',verified:true,badge:'阳光支教队·教学组长',teamName:'阳光支教队',location:'四川美姑'},createdAt:'2026-05-10'},
  { id:'cr5',title:'乡村小学运动会策划方案',description:'不需要标准跑道和器材的运动会方案。8个创意项目：纸飞机大赛、麻袋跳、运水接力、两人三足等。包含安全预案、评分表、奖状模板。在宁夏固原一所200平米操场的学校成功举办，89个孩子全部参与。',category:'activity',grade:'all',subject:'体育',fileType:'PDF',fileSize:'2.7MB',downloads:534,rating:4.6,teamName:'筑梦支教团',location:'宁夏固原',tags:['运动会','创意项目','安全预案','全年级'],author:{ id:'a4',name:'大鹏',avatar:'🦅',role:'volunteer',verified:true,badge:'筑梦支教团·副队长',teamName:'筑梦支教团',location:'宁夏固原'},createdAt:'2026-05-22'},
  { id:'cr6',title:'小学生性教育启蒙课教案',description:'用绘本为引子设计的两课时性教育启蒙课程。涵盖我从哪里来、身体的界限、遇到不舒服的触碰怎么办。语言温柔克制，已有8支支教队使用。',category:'lesson_plan',grade:'grade3-4',subject:'心理',fileType:'PDF',fileSize:'1.5MB',downloads:752,rating:4.9,teamName:'青苗助学计划',location:'甘肃天水',tags:['性教育','启蒙','身体安全'],author:{ id:'a5',name:'小芳',avatar:'🌿',role:'volunteer',verified:true,badge:'青苗助学计划·心理辅导员',teamName:'青苗助学计划',location:'甘肃天水'},createdAt:'2026-04-28',featured:true},
  { id:'cr7',title:'支教队出发前培训手册',description:'为第一次下乡支教的大学生准备的完整手册。涵盖出发前心理准备、与孩子的沟通技巧、课堂纪律管理10条、结营情感告别指南。12年支教经验浓缩成48页，被超过20支队伍用作新队员必读材料。',category:'handbook',grade:'all',subject:'通识',fileType:'PDF',fileSize:'4.2MB',downloads:1523,rating:4.9,teamName:'凡星支教队',location:'四川筠连',tags:['培训手册','新队员必读','12年经验','20+队伍使用'],author:{ id:'u1',name:'黄寒阳',avatar:'/images/community/author-volunteer-zhang.webp',role:'volunteer',verified:true,badge:'凡星支教队·队长',teamName:'凡星支教队',location:'四川筠连'},createdAt:'2026-02-10',featured:true},
  { id:'cr8',title:'苗族传统纹样美术课件',description:'以西双版纳苗族传统纹样为主题的美术课。学生用蜡笔和水彩重现苗族服饰上的几何图案。包含苗族纹样的文化含义讲解、10种基础纹样模板、配色方案。连接美术课与文化传承。',category:'ppt',grade:'grade3-4',subject:'美术',fileType:'PPT',fileSize:'15MB',downloads:421,rating:4.5,teamName:'彩云之南志愿队',location:'云南西双版纳',tags:['美术','苗族文化','传统纹样','文化传承'],author:{ id:'a2',name:'雪莉',avatar:'🌸',role:'volunteer',verified:true,badge:'彩云之南志愿队·队长',teamName:'彩云之南志愿队',location:'云南西双版纳'},createdAt:'2026-06-01'},
  { id:'cr9',title:'英语启蒙——26个字母趣味教学卡片',description:'把26个英文字母变成26种动物。每张卡片正面是字母+动物插画，背面是简单单词+发音提示。适合完全没有英语基础的乡村小学生。推荐彩色打印塑封后使用。',category:'worksheet',grade:'grade1-2',subject:'英语',fileType:'PDF',fileSize:'5.6MB',downloads:689,rating:4.6,teamName:'追光者支教队',location:'青海玉树',tags:['英语启蒙','字母','动物卡片','低年级'],author:{ id:'v10',name:'追光者支教队',avatar:'💫',role:'official',verified:true,badge:'追光者支教队·英语组',location:'青海玉树'},createdAt:'2026-05-15'},
  { id:'cr10',title:'小学生情绪管理小课堂',description:'基于CBT简化设计的6节情绪管理课。用情绪温度计、烦恼垃圾桶、快乐储蓄罐等具象化工具帮助留守儿童学会识别和表达情绪。每节课30分钟，不需要多媒体设备。',category:'lesson_plan',grade:'grade3-4',subject:'心理',fileType:'PDF',fileSize:'2.0MB',downloads:687,rating:4.8,teamName:'青苗助学计划',location:'甘肃天水',tags:['情绪管理','心理健康','留守儿童','CBT'],author:{ id:'a5',name:'小芳',avatar:'🌿',role:'volunteer',verified:true,badge:'青苗助学计划·心理辅导员',teamName:'青苗助学计划',location:'甘肃天水'},createdAt:'2026-03-20',featured:true},
  { id:'cr11',title:'乡村小学口算速算技巧大全',description:'7种口算技巧：凑十法、破十法、平十法、想加算减、乘法分配律巧用、除法的简便运算、估算技巧。每种技巧配10道练习题+答案。在四川凉山3所村小试用后学生口算速度平均提升35%。',category:'worksheet',grade:'grade3-4',subject:'数学',fileType:'PDF',fileSize:'1.9MB',downloads:567,rating:4.5,teamName:'阳光支教队',location:'四川美姑',tags:['口算','速算','技巧','练习题'],author:{ id:'a1',name:'婷婷',avatar:'🌻',role:'volunteer',verified:true,badge:'阳光支教队·教学组长',teamName:'阳光支教队',location:'四川美姑'},createdAt:'2026-04-05'},
  { id:'cr12',title:'纸戏剧——不需要PPT的讲故事方法',description:'纸戏剧用一张张抽拉的画卡讲故事。包含8个原创纸戏剧剧本含插图模板，主题涵盖诚信、勇气、友谊等。特别适合没有投影设备的乡村教室。只需要一个木框和打印好的画卡。',category:'activity',grade:'grade1-2',subject:'语文',fileType:'PDF',fileSize:'8.3MB',downloads:445,rating:4.7,teamName:'筑梦支教团',location:'宁夏固原',tags:['纸戏剧','讲故事','无设备','低年级'],author:{ id:'a4',name:'大鹏',avatar:'🦅',role:'volunteer',verified:true,badge:'筑梦支教团·副队长',teamName:'筑梦支教团',location:'宁夏固原'},createdAt:'2026-06-10'},
  { id:'cr13',title:'乡村小学科学评估量表',description:'一套不依赖纸笔测试的科学素养评估工具。包含观察记录表、动手操作评分标准、科学思维发展阶梯。设计理念：评估不是为了排名，而是为了发现每个孩子的思维闪光点。',category:'assessment',grade:'all',subject:'科学',fileType:'PDF',fileSize:'1.2MB',downloads:312,rating:4.4,teamName:'青苗助学计划',location:'甘肃天水',tags:['评估','科学素养','不排名','思维发展'],author:{ id:'a5',name:'小芳',avatar:'🌿',role:'volunteer',verified:true,badge:'青苗助学计划·科学组',teamName:'青苗助学计划',location:'甘肃天水'},createdAt:'2026-07-01'},
  { id:'cr14',title:'少数民族地区教学指南——文化回应性教学',description:'支教不是单向输出而是双向学习。详细介绍如何在课程中融入当地少数民族文化：先用访谈了解社区文化资产，再设计文化回应性教学。包含苗族、彝族、藏族、傣族四个民族的教学案例。',category:'handbook',grade:'all',subject:'通识',fileType:'PDF',fileSize:'3.5MB',downloads:523,rating:4.8,teamName:'彩云之南志愿队',location:'云南西双版纳',tags:['少数民族','文化回应','双向学习','四族案例'],author:{ id:'a2',name:'雪莉',avatar:'🌸',role:'volunteer',verified:true,badge:'彩云之南志愿队·队长',teamName:'彩云之南志愿队',location:'云南西双版纳'},createdAt:'2026-05-05'},
  { id:'cr15',title:'点亮第一盏灯——AI启蒙课教案',description:'用教计算机认动物的游戏化方式让乡村孩子零基础理解AI的基本概念。40分钟课程包含AI识图小游戏、训练数据概念体验、讨论环节。不需要编程基础只需要一部能拍照的手机。',category:'lesson_plan',grade:'grade5-6',subject:'科学',fileType:'PDF',fileSize:'2.8MB',downloads:891,rating:4.7,teamName:'凡星支教队',location:'四川筠连',tags:['AI启蒙','计算机','零基础','40分钟'],author:{ id:'u1',name:'黄寒阳',avatar:'/images/community/author-volunteer-zhang.webp',role:'volunteer',verified:true,badge:'凡星支教队·队长',teamName:'凡星支教队',location:'四川筠连'},createdAt:'2026-06-15',featured:true},
]

// ═══════════════════════════════════════
// 智能匹配 — 支教队档案
// ═══════════════════════════════════════
export const TEAM_PROFILES: TeamProfile[] = [
  { id:'t1',name:'凡星支教队',logo:'🌟',location:'四川宜宾筠连县',duration:'13天（7月）',teamSize:18,subjects:['科学','语文','数学','美术','音乐','体育','计算机'],description:'电子科技大学计算机学院11年品牌支教队，2026年深入筠连县城南+玉壶两个社区。五育并举课程体系，AI启蒙特色课程。',recruitmentStatus:'open',skillsNeeded:['编程教学','摄影摄像','文案写作'],contactInfo:'公众号: 凡星支教',matchScore:95,matchReasons:['你的家乡是四川','你擅长科学实验','你会摄影']},
  { id:'t2',name:'彩云之南志愿队',logo:'🌈',location:'云南西双版纳/怒江/迪庆',duration:'15天（8月）',teamSize:22,subjects:['民族文化','地理','语文','美术','英语'],description:'云南大学志愿队，6年专注边疆少数民族地区教育。以文化传承为核心。',recruitmentStatus:'urgent',skillsNeeded:['美术教学','民族文化研究','视频剪辑'],contactInfo:'公众号: 彩云之南志愿队'},
  { id:'t3',name:'筑梦支教团',logo:'🏗️',location:'宁夏固原/甘肃天水/陕西商洛',duration:'15-18天（7-8月）',teamSize:28,subjects:['AI启蒙','科技制作','历史故事','书法','体育'],description:'西安交通大学支教团，6年深耕陕甘宁革命老区。',recruitmentStatus:'open',skillsNeeded:['科技制作','书法教学','体育特长'],contactInfo:'公众号: 筑梦支教团'},
  { id:'t4',name:'阳光支教队',logo:'☀️',location:'四川凉山美姑县',duration:'14天（7月）',teamSize:15,subjects:['数学','语文','心理','体育'],description:'四川师范大学支教队，专注凉山彝族地区教育。',recruitmentStatus:'open',skillsNeeded:['心理咨询','数学教学','体育活动组织'],contactInfo:'微信: sunshine_edu'},
  { id:'t5',name:'青苗助学计划',logo:'🌱',location:'甘肃天水/定西',duration:'21天（7-8月）',teamSize:20,subjects:['科学','心理','美术','音乐','阅读'],description:'兰州大学长期支教项目，以阅读+科学双核驱动。',recruitmentStatus:'urgent',skillsNeeded:['阅读推广','科学实验','心理辅导'],contactInfo:'公众号: 青苗助学'},
  { id:'t6',name:'追光者支教队',logo:'💫',location:'青海玉树/果洛',duration:'20天（8月）',teamSize:16,subjects:['英语','语文','音乐','体育'],description:'青海本地大学生+外地志愿者混合编队，5年扎根青藏高原牧区。',recruitmentStatus:'open',skillsNeeded:['藏语基础','英语教学','高原适应'],contactInfo:'微信: zhuiguangzhe_team'},
]

// ── 贡献榜 ──
const BADGES: Record<string, ContributorBadge> = {
  answer_king: { id:'b1',name:'答题达人',emoji:'🎖',description:'累计获得100+点赞的回答',tier:'diamond',condition:'回答点赞≥100'},
  resource_master: { id:'b2',name:'资源共享家',emoji:'📦',description:'上传20+份教学资源',tier:'diamond',condition:'上传资源≥20'},
  story_teller: { id:'b3',name:'故事讲述者',emoji:'📸',description:'分享了5+篇支教故事',tier:'gold',condition:'故事≥5'},
  first_responder: { id:'b4',name:'快速响应',emoji:'⚡',description:'在问题发布24h内给出回答',tier:'silver',condition:'快速回答≥10'},
  veteran: { id:'b5',name:'支教老兵',emoji:'🦅',description:'参与支教3年以上',tier:'gold',condition:'教龄≥3'},
  bridge: { id:'b6',name:'搭桥者',emoji:'🌉',description:'帮助志愿者成功匹配队伍',tier:'silver',condition:'成功匹配≥5'},
}

export const CONTRIBUTOR_RANKINGS: ContributorRank[] = [
  { rank:1, score:2840, badges:[BADGES.answer_king,BADGES.resource_master,BADGES.veteran],highlights:['回答了34个问题','上传了15份教案','帮助了500+名老师'],author:{ id:'v2',name:'李老师',avatar:'📚',role:'volunteer',verified:true,badge:'一线教师 · 28年教龄',teamName:'宜宾市翠屏区实验小学',location:'四川宜宾'}},
  { rank:2, score:2150, badges:[BADGES.resource_master,BADGES.story_teller],highlights:['上传了25份资源','写了8篇支教故事','总下载量3000+'],author:{ id:'u1',name:'黄寒阳',avatar:'/images/community/author-volunteer-zhang.webp',role:'volunteer',verified:true,badge:'凡星支教队·队长',teamName:'凡星支教队',location:'四川筠连'}},
  { rank:3, score:1890, badges:[BADGES.answer_king,BADGES.first_responder],highlights:['回答了28个问题','平均30分钟给出回复','累计收获240+点赞'],author:{ id:'v3',name:'王教师',avatar:'👨',role:'volunteer',verified:true,badge:'退休教师 · 支教顾问',teamName:'阳光支教队',location:'四川美姑'}},
  { rank:4, score:1620, badges:[BADGES.bridge,BADGES.story_teller],highlights:['帮助12人匹配到支教队','写了6篇支教故事','组织了4次线上分享'],author:{ id:'a2',name:'雪莉',avatar:'🌸',role:'volunteer',verified:true,badge:'彩云之南志愿队·队长',teamName:'彩云之南志愿队',location:'云南西双版纳'}},
  { rank:5, score:1480, badges:[BADGES.first_responder],highlights:['回答了18个问题','快速响应率95%','平均点赞数8.5'],author:{ id:'a1',name:'婷婷',avatar:'🌻',role:'volunteer',verified:true,badge:'阳光支教队·教学组长',teamName:'阳光支教队',location:'四川美姑'}},
  { rank:6, score:1320, badges:[BADGES.resource_master],highlights:['上传了12份心理教案','累计下载量1800+','被5支队伍采纳'],author:{ id:'a5',name:'小芳',avatar:'🌿',role:'volunteer',verified:true,badge:'青苗助学计划·心理辅导员',teamName:'青苗助学计划',location:'甘肃天水'}},
  { rank:7, score:1050, badges:[BADGES.story_teller,BADGES.bridge],highlights:['写了7篇支教故事','帮助8人匹配队伍','故事总阅读量5000+'],author:{ id:'a4',name:'大鹏',avatar:'🦅',role:'volunteer',verified:true,badge:'筑梦支教团·副队长',teamName:'筑梦支教团',location:'宁夏固原'}},
]
