'use client'
import Link from 'next/link'
import { useState } from 'react'
import { Card, CardContent } from '@/components/ui/card'
import { ROLE_LABELS, UserRole } from '@/types'
export default function RegisterPage() {
  const [step, setStep] = useState(1)
  const [roles, setRoles] = useState<UserRole[]>([])
  const toggleRole=(r:UserRole)=>{setRoles(prev=>prev.includes(r)?prev.filter(x=>x!==r):[...prev,r])}
  return (<div className="min-h-screen flex items-center justify-center p-6" style={{background:'linear-gradient(135deg,#2E7D32 0%,#4CAF50 40%,#81C784 100%)'}}>
    <Card className="w-full max-w-[440px] border-0 shadow-2xl"><CardContent className="p-8">
      <div className="flex items-center gap-2 mb-6">{[1,2,3].map(s=>(<div key={s} className={`flex items-center gap-2 ${step>=s?'text-[var(--primary)]':'text-[var(--text-muted)]'}`}><div className={`w-6 h-6 rounded-full flex items-center justify-center text-[11px] font-semibold ${step>=s?'bg-[var(--primary)] text-white':'bg-[var(--bg)] text-[var(--text-muted)] border border-[var(--border)]'}`}>{s}</div>{s<3&&<div className="w-8 h-px bg-[var(--border)]"/>}</div>))}</div>
      {step===1&&<div><h2 className="text-[18px] font-semibold text-[var(--text)] mb-4">选择身份</h2><p className="text-[12px] text-[var(--text-muted)] mb-4">可多选，支持一人多身份</p><div className="space-y-2">{(Object.keys(ROLE_LABELS) as UserRole[]).map(r=>(<button key={r} onClick={()=>toggleRole(r)} className={`w-full p-3 rounded-xl border text-left text-[13px] font-medium transition-all ${roles.includes(r)?'border-[var(--primary)] bg-[var(--primary)]/5 text-[var(--primary)]':'border-[var(--border)] text-[var(--text-secondary)] hover:border-[var(--primary)]/30'}`}>{ROLE_LABELS[r]}</button>))}</div><button onClick={()=>setStep(2)} disabled={roles.length===0} className="w-full mt-4 py-2.5 rounded-xl bg-[var(--primary)] text-white text-[13px] font-medium border-none cursor-pointer disabled:opacity-50">下一步</button></div>}
      {step===2&&<div><h2 className="text-[18px] font-semibold text-[var(--text)] mb-4">填写信息</h2><div className="space-y-3"><input placeholder="姓名" defaultValue="黄寒阳" className="w-full px-4 py-2.5 rounded-xl border border-[var(--border)] bg-[var(--bg)] text-[13px] outline-none focus:border-[var(--primary)]"/><input placeholder="邮箱" defaultValue="huang@uestc.edu.cn" className="w-full px-4 py-2.5 rounded-xl border border-[var(--border)] bg-[var(--bg)] text-[13px] outline-none focus:border-[var(--primary)]"/><input type="password" placeholder="密码" defaultValue="123456" className="w-full px-4 py-2.5 rounded-xl border border-[var(--border)] bg-[var(--bg)] text-[13px] outline-none focus:border-[var(--primary)]"/></div><div className="flex gap-3 mt-4"><button onClick={()=>setStep(1)} className="flex-1 py-2.5 rounded-xl border border-[var(--border)] text-[var(--text-secondary)] text-[13px] bg-transparent cursor-pointer">上一步</button><button onClick={()=>setStep(3)} className="flex-1 py-2.5 rounded-xl bg-[var(--primary)] text-white text-[13px] font-medium border-none cursor-pointer">下一步</button></div></div>}
      {step===3&&<div className="text-center"><div className="text-5xl mb-4">🎉</div><h2 className="text-[18px] font-semibold text-[var(--text)] mb-2">注册成功！</h2><p className="text-[13px] text-[var(--text-muted)] mb-6">欢迎加入支教星火全国平台</p><Link href="/dashboard" className="inline-block px-8 py-2.5 rounded-xl bg-[var(--primary)] text-white text-[13px] font-medium no-underline">进入支教星火</Link></div>}
    </CardContent></Card></div>)
}
